version: "3"

services:

  vue-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

    volumes:
      - ./:/app
      - /app/node_modules

  mysql:
    platform: linux/x86_64
    image: mysql
    # volumes:
    #   - /db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"

    